query Restaurants {
  restaurants {
    data {
      id
      attributes {
        name
        image {
          data {
            attributes {
              url
              alternativeText
            }
          }
        }
      }
    }
  }
}
